### ISSUE TITLE
regex fails if abbreviated hash is longer than 7 characters

### ISSUE THREAD

**Issue by kcivey** [mikaelkaron/grunt-git-describe#18]
I just ran into a situation where grunt-git-describe was giving weird output. I had a commit tagged as `v1.0.23` with a commit hash of `171d4da48514131848beb820513afff74682adbc`, and the output was coming out as `--71d4da4` (two hyphens plus the 2nd through 8th characters of the hash).

There were two commits in my repo that had the same initial 7 characters, so `git describe` was using 8 characters for the abbreviated hash in its output: `v1.0.23-0-g171d4da4`. When the regex `/(?:(.*)-(\d+)-g)?([a-fA-F0-9]{7})(-dirty)?$/` is applied, it has no anchor at the start, so only the last 7 characters get matched.

A solution would be to allow a longer abbreviated hash in the regex, by changing

```
var RE =/(?:(.*)-(\d+)-g)?([a-fA-F0-9]{7})(-dirty)?$/;
```

to

```
var RE =/(?:(.*)-(\d+)-g)?([a-fA-F0-9]{7,40})(-dirty)?$/;
```

It's probably also a good idea to anchor it at the start:

```
var RE =/^(?:(.*)-(\d+)-g)?([a-fA-F0-9]{7,40})(-dirty)?$/;
```

**Comment by mikaelkaron** [comment]
you are correct, the RE needs to change. Would you like to submit a patch for some credz?
