### ISSUE TITLE
Warning: Expected a function Use --force to continue.

### ISSUE THREAD

**Issue by elfin-sbreuers** [mikaelkaron/grunt-git-describe#20]
Hello,

I am encountering the following issue:

When I create the following gruntfile

``` javascript
module.exports = function (grunt) {
   'use strict';
   grunt.initConfig({
        'git-describe': {
            me: { }
        }
    });

    grunt.task.loadNpmTasks('grunt-git-describe');
};
```

and install with 

`npm install grunt-git-describe grunt`

the necessary dependencies.

The call of

`grunt git-describe`

gives the following error:

``` shell
Running "git-describe:me" (git-describe) task
Warning: Expected a function Use --force to continue.

Aborted due to warnings.
```

 Does anyone have an idea how to solve this issue?

Kind regards,

Sebastian

**Comment by mikaelkaron** [comment]
I have to be honest it's been ages since I looked at this. I'll try to take a look at this ASAP to help out.

**Comment by LeeGDavis** [comment]
We're running into this issue under the same circumstances.  If there is any additional information I can provide to help chase down a solution please let me know.

**Comment by LeeGDavis** [comment]
Added the following to PR's to address the issue of using lodash 4.x found in grunt 1.x

https://github.com/mikaelkaron/grunt-util-process/pull/2
https://github.com/mikaelkaron/grunt-util-options/pull/3

 * Changed lodash `rest` usage to `tail`.
  * Note this still supports lodash 3.x as tail was an alias for the original rest.  Both 3.x and 4.x tail do the same thing.
