### ISSUE TITLE
AWS CodeBuild

### ISSUE THREAD

**Issue by fmieres** [mikaelkaron/grunt-git-describe#24]
has ever happened to you using codecommit + codebuild, that this task only brings revision object ? (it doesn't get tag, dirty status ). I've already pushed some tags to codecommit.  (I have no trouble using codecommit and building in my machine).

Any suggestion ?

Thanks in advance.

**Comment by mikaelkaron** [comment]
I'm not sure I understand the problem. Do you have a reproducible example I can try?

**Comment by fmieres** [comment]
I'm sorry, you can close this one. It started working out of nowhere. Suddenly builds in CodeBuild started getting the correct info. I don't get it yet, but now it works.
